# Generated by Django 4.2.4 on 2023-10-28 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_quip_parent_quip'),
    ]

    operations = [
        migrations.AddField(
            model_name='quip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
